config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :raw_materials, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/raw_material.rb
class RawMaterial < ApplicationRecord
  CATEGORIES = [
    'Base Oils',
    'Essential Oils',
    'Lye',
    'Liquids',
    'Colorants',
    'Additives',
  ]

  validates :name, presence: true, uniqueness: true
  validates_inclusion_of :category, in: CATEGORIES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/raw_materials_controller.rb
class RawMaterialsController < ApplicationController

  def index
    @raw_materials = RawMaterial.all
    @categories = RawMaterial::CATEGORIES
  end

  def new
    @raw_material = RawMaterial.new
  end

  def create
    @raw_material = RawMaterial.new(raw_material_params)
    if @raw_material.save
      redirect_to raw_materials_url
    else
      render :new
    end
  end

  private

  def raw_material_params
    params.require(:raw_material).permit(
      :name,
      :category,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soapmaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/raw_materials/index.html.erb
<%= link_to "Add Raw Material", new_raw_material_path %>
<% @categories.each do |category| %>
  <div data-category="<%= category %>">
    <h3><%= category %></h3>
    <ul>
      <% @raw_materials.each do |raw_material| %>
        <% if raw_material.category == category %>
          <li><%= raw_material.name %></li>
        <% end%>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/raw_materials/new.html.erb
<p><%= @raw_material.errors.full_messages.join(', ') %></p>
<%= form_for @raw_material do |f| %>
  <%= f.text_field :name %>
  <%= f.select :category, RawMaterial::CATEGORIES %>
  <%= f.submit 'Submit' %>
<% end %>